name: Build and upload artifact

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 1'  # Co tydzień w poniedziałek
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install lxml pyyaml
      shell: bash

    - name: Run pyinstaller
      run: pyinstaller --onefile --noconsole src/main.py
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-executable
        path: dist/main.exe
